import { ArrowLeft, BriefcaseBusiness, CalendarDays, ChevronRight, Filter, MapPin, Maximize2, Phone, RotateCcw, Search, X } from "lucide-react";
import { useEffect, useState } from "react";
import { marketers } from "../data/marketers";
import { prospects } from "../data/prospects";
import { visitReports } from "../data/visitReports";
import { getMarketingName, getProspectName } from "../utils/dataRelations";

type Navigate=(name:string,params?:Record<string,unknown>)=>void;
type CommonProps={day:string;navigate:Navigate;back:()=>void};
const dateText=(value?:string)=>value?new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${value}T00:00:00`)):"—";
const statusTone=(value:string)=>["Selesai","Tersinkronisasi","Transaksi Selesai"].includes(value)?"bg-emerald-400/10 text-emerald-300":value==="Gagal"||value==="Tidak Tertarik"?"bg-red-400/10 text-red-300":"bg-amber-400/10 text-amber-300";
const Badge=({value}:{value:string})=><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold ${statusTone(value)}`}>{value}</span>;

function Header({title,subtitle,back}:{title:string;subtitle:string;back:()=>void}) {
  return <div className="mb-5 flex items-center gap-3"><button onClick={back} aria-label="Kembali" className="grid size-11 shrink-0 place-items-center rounded-xl border border-white/[.08] bg-white/[.035] text-[#AAB2BE]"><ArrowLeft size={19}/></button><div><h1 className="text-xl font-semibold text-white sm:text-2xl">{title}</h1><p className="mt-0.5 text-xs text-[#7E8896]">{subtitle}</p></div></div>;
}
function SearchBox({value,setValue}:{value:string;setValue:(value:string)=>void}) {
  return <label className="flex min-h-11 items-center gap-3 rounded-xl border border-white/[.08] bg-[#11171F] px-3"><Search size={16} className="text-[#687483]"/><input value={value} onChange={event=>setValue(event.target.value)} placeholder="Cari data..." className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none"/></label>;
}
function Select({value,onChange,children,label}:{value:string;onChange:(value:string)=>void;children:React.ReactNode;label:string}) {
  return <label className="min-w-0"><span className="mb-1 block text-[10px] font-semibold uppercase tracking-[.07em] text-[#697483]">{label}</span><select value={value} onChange={event=>onChange(event.target.value)} className="min-h-11 w-full rounded-xl border border-white/[.08] bg-[#11171F] px-3 text-xs text-[#DDE2E7] outline-none">{children}</select></label>;
}
function Section({title,children}:{title:string;children:React.ReactNode}) {
  return <section className="rounded-2xl border border-white/[.07] bg-[#0D131A] p-4 sm:p-5"><h2 className="mb-4 text-sm font-semibold text-[#E8C65A]">{title}</h2><div className="grid gap-4 sm:grid-cols-2">{children}</div></section>;
}
function Field({label,value,wide=false}:{label:string;value:React.ReactNode;wide?:boolean}) {
  return <div className={wide?"sm:col-span-2":""}><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#687483]">{label}</p><div className="mt-1.5 text-sm leading-6 text-[#E5E9ED]">{value||"—"}</div></div>;
}

export function ProspectListPage({day,navigate,back}:CommonProps) {
  const [query,setQuery]=useState(""); const [marketing,setMarketing]=useState("Semua"); const [status,setStatus]=useState("Semua"); const [resort,setResort]=useState("Semua"); const [filtersOpen,setFiltersOpen]=useState(false);
  const rows=prospects.filter(item=>item.day===day&&(marketing==="Semua"||item.marketingId===marketing)&&(status==="Semua"||item.status===status)&&(resort==="Semua"||item.resort===resort)&&`${item.name} ${item.phone} ${item.business}`.toLowerCase().includes(query.toLowerCase()));
  const reset=()=>{setQuery("");setMarketing("Semua");setStatus("Semua");setResort("Semua");};
  const controls=<><Select label="Marketing" value={marketing} onChange={setMarketing}><option>Semua</option>{marketers.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</Select><Select label="Status" value={status} onChange={setStatus}><option>Semua</option>{["Baru","Tertarik","Perlu Follow Up","Tidak Tertarik","Selesai"].map(item=><option key={item}>{item}</option>)}</Select><Select label="Resort" value={resort} onChange={setResort}><option>Semua</option>{[...new Set(prospects.map(item=>item.resort))].map(item=><option key={item}>{item}</option>)}</Select></>;
  return <div className="px-4 pb-24 pt-5 sm:px-6 lg:px-8 lg:pb-8">
    <Header title="Data Prospek" subtitle="Data prospek dan calon anggota yang dicatat marketing." back={back}/>
    <div className="mb-4 flex gap-2 lg:hidden"><div className="min-w-0 flex-1"><SearchBox value={query} setValue={setQuery}/></div><button onClick={()=>setFiltersOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/[.08] bg-[#11171F] px-3 text-xs text-white"><Filter size={16}/>Filter</button></div>
    <div className="mb-4 hidden grid-cols-6 items-end gap-3 lg:grid"><div className="col-span-2"><SearchBox value={query} setValue={setQuery}/></div>{controls}<button onClick={reset} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/[.08] text-xs text-[#AAB2BE]"><RotateCcw size={14}/>Reset</button></div>
    <p className="mb-3 text-xs text-[#7E8896]">{rows.length} data · {day}{marketing!=="Semua"?` · ${getMarketingName(marketing)}`:""}{status!=="Semua"?` · ${status}`:""}</p>
    <div className="space-y-3 lg:hidden">{rows.map(item=><button key={item.id} onClick={()=>navigate("ProspectDetail",{id:item.id})} className="flex w-full items-center gap-3 rounded-2xl border border-white/[.07] bg-[#0D131A] p-4 text-left"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-[#D4AF37]/10 font-semibold text-[#E8C65A]">{item.name.slice(0,1)}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-white">{item.name}</strong><span className="mt-1 block text-xs text-[#7E8896]">{item.phone} · {item.business}</span><span className="mt-2 flex flex-wrap gap-2"><Badge value={item.status}/><span className="text-[10px] text-[#788391]">{getMarketingName(item.marketingId)} · {item.resort}</span></span><span className="mt-2 block text-[10px] text-[#697483]">Kunjungan terakhir: {dateText(item.lastVisitDate)}</span></span><ChevronRight size={17} className="text-[#66717E]"/></button>)}</div>
    <div className="hidden overflow-x-auto rounded-2xl border border-white/[.08] lg:block"><table className="w-full min-w-[1350px] text-left text-xs"><thead className="bg-[#151C25] text-[#E8C65A]"><tr>{["No","Nama Prospek","Nomor HP","Usaha","Status","Marketing","Resort","Tanggal Input","Kunjungan Terakhir","Sinkronisasi","Aksi"].map(label=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.map((item,index)=><tr key={item.id} className="border-t border-white/[.06] text-[#DCE1E6] hover:bg-white/[.025]"><td className="px-4 py-3">{index+1}</td><td className="px-4 py-3 font-semibold text-white">{item.name}</td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3">{item.business}</td><td className="px-4 py-3"><Badge value={item.status}/></td><td className="px-4 py-3">{getMarketingName(item.marketingId)}</td><td className="px-4 py-3">{item.resort}</td><td className="px-4 py-3">{dateText(item.date)} · {item.time}</td><td className="px-4 py-3">{dateText(item.lastVisitDate)}</td><td className="px-4 py-3">{item.syncStatus}</td><td className="px-4 py-3"><button onClick={()=>navigate("ProspectDetail",{id:item.id})} className="font-semibold text-[#E8C65A]">Detail</button></td></tr>)}</tbody></table></div>
    {!rows.length&&<div className="rounded-2xl border border-dashed border-white/[.1] py-14 text-center text-sm text-[#7E8896]">Belum ada data prospek pada hari {day}.</div>}
    {filtersOpen&&<><button aria-label="Tutup filter" onClick={()=>setFiltersOpen(false)} className="fixed inset-0 z-[1500] bg-black/70"/><div className="fixed inset-x-0 bottom-0 z-[1510] rounded-t-3xl border-t border-white/[.1] bg-[#0D131A] p-5"><div className="mb-4 flex items-center justify-between"><strong className="text-white">Filter Prospek</strong><button onClick={()=>setFiltersOpen(false)}><X size={19}/></button></div><div className="grid gap-3">{controls}</div><div className="mt-5 flex gap-3"><button onClick={reset} className="min-h-11 flex-1 rounded-xl border border-white/[.1] text-xs text-white">Reset</button><button onClick={()=>setFiltersOpen(false)} className="min-h-11 flex-1 rounded-xl bg-[#D4AF37] text-xs font-semibold text-[#080B10]">Terapkan</button></div></div></>}
  </div>;
}

export function ProspectDetailPage({id,back,navigate}:{id:string;back:()=>void;navigate:Navigate}) {
  const item=prospects.find(row=>row.id===id); if(!item)return <Header title="Detail Prospek" subtitle="Data tidak ditemukan" back={back}/>;
  const visits=visitReports.filter(row=>row.prospectId===item.id);
  return <div className="space-y-4"><Header title={item.name} subtitle={`${item.id} · ${item.resort}`} back={back}/><div className="flex flex-wrap gap-2"><Badge value={item.status}/><Badge value={item.syncStatus}/></div>
    {item.linkedMemberId&&<div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[.07] p-4 text-sm text-emerald-200">Prospek ini sudah terdaftar sebagai anggota. <button onClick={()=>navigate("AnggotaDetail",{id:item.linkedMemberId})} className="ml-2 font-semibold underline">Lihat Data Anggota</button></div>}
    <Section title="Informasi Prospek"><Field label="Nomor HP" value={<span className="inline-flex gap-2"><Phone size={14}/>{item.phone}</span>}/><Field label="Usaha / pekerjaan" value={<span className="inline-flex gap-2"><BriefcaseBusiness size={14}/>{item.business}</span>}/><Field label="Alamat" value={item.address} wide/><Field label="Status" value={item.status}/><Field label="Hasil awal kunjungan" value={item.initialVisitResult}/><Field label="Catatan" value={item.notes||"Tidak ada catatan"} wide/></Section>
    <Section title="Marketing dan Lokasi"><Field label="Marketing" value={`${item.marketingId} · ${getMarketingName(item.marketingId)}`}/><Field label="Resort" value={item.resort}/><Field label="Lokasi" value={<span className="inline-flex gap-2"><MapPin size={14}/>{item.locationAddress}</span>} wide/><Field label="Tanggal" value={dateText(item.date)}/><Field label="Waktu" value={item.time}/><Field label="Sinkronisasi" value={item.syncStatus} wide/></Section>
    <Section title={`Riwayat Laporan Kunjungan (${visits.length})`}>{visits.map(visit=><button key={visit.id} onClick={()=>navigate("VisitReportDetail",{id:visit.id})} className="rounded-xl border border-white/[.08] p-3 text-left"><strong className="block text-sm text-white">{visit.visitPurpose}</strong><span className="mt-1 block text-xs text-[#7E8896]">{dateText(visit.date)} · {visit.time} · {visit.visitResult}</span></button>)}</Section>
    <div className="grid gap-2 sm:grid-cols-3"><button onClick={()=>navigate("MarketingDetail",{id:item.marketingId})} className="min-h-11 rounded-xl bg-[#D4AF37] text-xs font-semibold text-[#080B10]">Lihat Marketing</button><button onClick={()=>navigate("VisitReportList",{prospectId:item.id})} className="min-h-11 rounded-xl border border-white/[.1] text-xs text-white">Lihat Riwayat Kunjungan</button><button className="min-h-11 rounded-xl border border-white/[.1] text-xs text-white">Lihat Lokasi</button></div>
  </div>;
}

export function VisitReportListPage({day,navigate,back}:CommonProps) {
  const [query,setQuery]=useState("");const [marketing,setMarketing]=useState("Semua");const [result,setResult]=useState("Semua");const [status,setStatus]=useState("Semua");
  const rows=visitReports.filter(item=>item.day===day&&(marketing==="Semua"||item.marketingId===marketing)&&(result==="Semua"||item.visitResult===result)&&(status==="Semua"||item.prospectStatus===status)&&`${getProspectName(item.prospectId)} ${item.visitPurpose}`.toLowerCase().includes(query.toLowerCase()));
  return <div><Header title="Laporan Kunjungan" subtitle="Laporan hasil kunjungan marketing kepada prospek." back={back}/><div className="mb-4 grid gap-3 lg:grid-cols-5"><div className="lg:col-span-2"><SearchBox value={query} setValue={setQuery}/></div><Select label="Marketing" value={marketing} onChange={setMarketing}><option>Semua</option>{marketers.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</Select><Select label="Hasil Kunjungan" value={result} onChange={setResult}><option>Semua</option>{["Berhasil Bertemu","Tidak Bertemu","Transaksi Selesai"].map(item=><option key={item}>{item}</option>)}</Select><Select label="Status Prospek" value={status} onChange={setStatus}><option>Semua</option>{["Baru","Tertarik","Perlu Follow Up","Tidak Tertarik","Selesai"].map(item=><option key={item}>{item}</option>)}</Select></div>
    <div className="space-y-3 lg:hidden">{rows.map(item=><button key={item.id} onClick={()=>navigate("VisitReportDetail",{id:item.id})} className="flex w-full gap-3 rounded-2xl border border-white/[.07] bg-[#0D131A] p-4 text-left"><img src={item.photo} alt={item.photoCaption} className="size-16 rounded-xl bg-[#151C25] object-cover"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-white">{getProspectName(item.prospectId)}</strong><span className="mt-1 block text-xs text-[#7E8896]">{getMarketingName(item.marketingId)} · {item.visitPurpose}</span><span className="mt-2 flex flex-wrap gap-2"><Badge value={item.visitResult}/><Badge value={item.prospectStatus}/></span><span className="mt-2 block text-[10px] text-[#697483]">{item.locationAddress} · {dateText(item.date)} {item.time}</span></span><ChevronRight size={17} className="text-[#66717E]"/></button>)}</div>
    <div className="hidden overflow-x-auto rounded-2xl border border-white/[.08] lg:block"><table className="w-full min-w-[1550px] text-left text-xs"><thead className="bg-[#151C25] text-[#E8C65A]"><tr>{["No","Foto","Prospek","Marketing","Tujuan","Hasil","Status Prospek","Resort","Lokasi","Tanggal","Waktu","Sinkronisasi","Aksi"].map(label=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.map((item,index)=><tr key={item.id} className="border-t border-white/[.06] text-[#DCE1E6]"><td className="px-4 py-3">{index+1}</td><td className="px-4 py-3"><img src={item.photo} alt="" className="size-10 rounded-lg object-cover"/></td><td className="px-4 py-3 font-semibold text-white">{getProspectName(item.prospectId)}</td><td className="px-4 py-3">{getMarketingName(item.marketingId)}</td><td className="px-4 py-3">{item.visitPurpose}</td><td className="px-4 py-3"><Badge value={item.visitResult}/></td><td className="px-4 py-3"><Badge value={item.prospectStatus}/></td><td className="px-4 py-3">{item.resort}</td><td className="px-4 py-3">{item.locationAddress}</td><td className="px-4 py-3">{dateText(item.date)}</td><td className="px-4 py-3">{item.time}</td><td className="px-4 py-3">{item.syncStatus}</td><td className="px-4 py-3"><button onClick={()=>navigate("VisitReportDetail",{id:item.id})} className="font-semibold text-[#E8C65A]">Detail</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="rounded-2xl border border-dashed border-white/[.1] py-14 text-center text-sm text-[#7E8896]">Belum ada laporan kunjungan pada hari {day}.</div>}</div>;
}

export function VisitReportDetailPage({id,back,navigate}:{id:string;back:()=>void;navigate:Navigate}) {
  const [photoOpen,setPhotoOpen]=useState(false);const item=visitReports.find(row=>row.id===id);const prospect=item?prospects.find(row=>row.id===item.prospectId):undefined;
  useEffect(()=>{if(!photoOpen)return;const close=(event:KeyboardEvent)=>event.key==="Escape"&&setPhotoOpen(false);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[photoOpen]);
  if(!item)return <Header title="Detail Laporan Kunjungan" subtitle="Data tidak ditemukan" back={back}/>;
  return <div className="space-y-4"><Header title="Detail Laporan Kunjungan" subtitle={`${item.id} · ${getProspectName(item.prospectId)}`} back={back}/><Section title="Prospek dan Marketing"><Field label="Prospek" value={prospect?.name}/><Field label="Nomor HP" value={prospect?.phone}/><Field label="Usaha" value={prospect?.business}/><Field label="Marketing" value={`${item.marketingId} · ${getMarketingName(item.marketingId)}`}/></Section><Section title="Hasil Kunjungan"><Field label="Tujuan kunjungan" value={item.visitPurpose}/><Field label="Hasil kunjungan" value={<Badge value={item.visitResult}/>}/><Field label="Status prospek" value={<Badge value={item.prospectStatus}/>}/><Field label="Tanggal follow up" value={dateText(item.followUpDate)}/><Field label="Catatan" value={item.notes||"Tidak ada catatan"} wide/></Section><Section title="Foto Kunjungan"><div className="sm:col-span-2"><img src={item.photo} alt={item.photoCaption} className="max-h-80 w-full rounded-xl bg-[#151C25] object-contain"/><p className="mt-2 text-xs text-[#7E8896]">{item.photoCaption}</p></div></Section><Section title="Lokasi dan Sistem"><Field label="Resort" value={item.resort}/><Field label="Lokasi" value={item.locationAddress}/><Field label="Koordinat" value={item.latitude&&item.longitude?`${item.latitude}, ${item.longitude}`:"—"}/><Field label="Tanggal & waktu" value={`${dateText(item.date)} · ${item.time}`}/><Field label="Sinkronisasi" value={item.syncStatus} wide/></Section><div className="grid gap-2 sm:grid-cols-4"><button onClick={()=>navigate("ProspectDetail",{id:item.prospectId})} className="min-h-11 rounded-xl bg-[#D4AF37] text-xs font-semibold text-[#080B10]">Lihat Data Prospek</button><button onClick={()=>navigate("MarketingDetail",{id:item.marketingId})} className="min-h-11 rounded-xl border border-white/[.1] text-xs text-white">Lihat Marketing</button><button className="min-h-11 rounded-xl border border-white/[.1] text-xs text-white">Lihat Lokasi</button><button onClick={()=>setPhotoOpen(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/[.1] text-xs text-white"><Maximize2 size={14}/>Perbesar Foto</button></div>{photoOpen&&<div className="fixed inset-0 z-[3000] grid place-items-center bg-black/90 p-4"><button onClick={()=>setPhotoOpen(false)} className="absolute right-4 top-4 grid size-11 place-items-center rounded-xl bg-white/10 text-white"><X/></button><img src={item.photo} alt={item.photoCaption} className="max-h-[90vh] max-w-full object-contain"/></div>}</div>;
}
